IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RT_REGIST_FILE_EXPEDITION_REPORT_LIST]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[RT_REGIST_FILE_EXPEDITION_REPORT_LIST] AS' 
END
GO
ALTER PROCEDURE [dbo].[RT_REGIST_FILE_EXPEDITION_REPORT_LIST] 
	@FileList IDPairList READONLY
AS
	SET NOCOUNT ON

	DECLARE @RequestID int

	BEGIN TRANSACTION
	SELECT @RequestID = ISNULL(MAX(RequestID),0) + 1
	FROM [dbo].[RTT_FILE_EXPEDITION_REPORT_LIST] WITH(TABLOCKX)

	INSERT INTO [dbo].[RTT_FILE_EXPEDITION_REPORT_LIST](RequestID, RunID, FileID)
	SELECT DISTINCT @RequestID, ID1, ID2
	FROM @FileList

	IF @@ROWCOUNT = 0
		SET @RequestID = 0
	COMMIT TRANSACTION

RETURN @RequestID
GO