IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RD_UX_SET_DOCCODE_AGGREGATION]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[RD_UX_SET_DOCCODE_AGGREGATION] AS' 
END
GO
ALTER  PROCEDURE [dbo].[RD_UX_SET_DOCCODE_AGGREGATION]
	@DocCodeID int,
	@DocCodeList IDList READONLY
--WITH ENCRYPTION
AS
	SET NOCOUNT ON
	BEGIN TRANSACTION

	DELETE RD_DOCCODE_AGGREGATION_COMPATIBILITY
	WHERE RefDocCodeID = @DocCodeID
	IF (@@ERROR <> 0)
		GOTO RBack

	DELETE RD_DOCCODE_AGGREGATION_COMPATIBILITY
	WHERE AggDocCodeID = @DocCodeID
	IF (@@ERROR <> 0)
		GOTO RBack

	INSERT INTO RD_DOCCODE_AGGREGATION_COMPATIBILITY(RefDocCodeID, AggDocCodeID)
	SELECT DISTINCT @DocCodeID, [ID]
	FROM @DocCodeList
	IF (@@ERROR <> 0)
		GOTO RBack

	INSERT INTO RD_DOCCODE_AGGREGATION_COMPATIBILITY(RefDocCodeID, AggDocCodeID)
	SELECT DISTINCT [ID], @DocCodeID
	FROM @DocCodeList
	IF (@@ERROR <> 0)
		GOTO RBack

	COMMIT TRANSACTION
RETURN
rBack:
	ROLLBACK TRANSACTION

GO
